[template]
cargo_generate_version = ">=0.17.4"
ignore = [".git"]

[hooks]
pre = ["pre-script.rhai"]

[placeholders.templatetype]
type = "string"
prompt = "chose a template type"
choices = ["node", "msgs", "node & msgs"]
default = "node"

[conditional.'templatetype == "node"']
ignore = ["r2r_minimal_node_msgs/"]

[conditional.'templatetype == "msgs"']
ignore = ["r2r_minimal_node/"]
