[template]
cargo_generate_version = ">=0.17.4"
ignore = [".git", "Cargo.lock", "target"]

[hooks]
pre = ["pre-script.rhai"]

[placeholders.template_type]
type = "string"
prompt = "chose a template"
choices = ["node", "msgs"]
default = "node"

[conditional.'template_type != "node"']
ignore = [".cargo", "src/", "Cargo.toml", "dummy.c", "r2r_carge.cmake"]

[conditional.'template_type != "msgs"']
ignore = ["action/", "msg/", "srv/"]


[conditional.'template_type == "node"'.placeholders.use_std_msgs]
type = "bool"
prompt = "will your node use std msgs?"
default = true

[conditional.'template_type == "node"'.placeholders.use_additonal_msgs]
type = "bool"
prompt = "will your node use custom msgs?"
default = false

[conditional.use_additonal_msgs.placeholders.additonal_msgs]
type = "string"
prompt = "what's your custom msgs name?"